#!/usr/bin/env bash

# Check if an argument is passed
if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Retrieve IP address |  from the first argument
IP_ADDRESS=$1

# Pings the IP address five times
ping -c 5 $IP_ADDRESS
